cities:
  - Los Angeles
  - San Francisco
  - Boston
  - New York 
  - Washington 
  - Seattle
  - Austin
  - Chicago
  - San Diego
  - Denver
  - London
  - Toronto
  - Sydney
  - Melbourne 
  - Paris 
  - Singapore
api_key: AIzaSyAGKceW-GbD7ymZCdNLIkPrKyAfgr_Ilrw
api_key2: AIzaSyCgGoDI5vj_TgLkWd5uu2xF9za7lc7z2yE
